version: "3.8"
services:
  frontend:
    image: python:3.11-slim
    container_name: dummy_frontend
    working_dir: /app
    volumes:
      - ./nginx/frontend:/app
    command: ["python", "-m", "http.server", "3000"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 5s
      retries: 5

  backend:
    image: python:3.11-slim
    container_name: dummy_backend
    working_dir: /app
    volumes:
      - ./nginx/backend:/app
    command: ["python", "-m", "http.server", "5000"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 5s
      retries: 5

  nginx:
    image: nginx:1.25-alpine
    container_name: proxy_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
